---
# tasks file for base
- name: Create download directory
  file:
    path: "{{ download_path }}"
    state: directory

- name: Check if Gentoo Stage 3 tarball exists
  ansible.builtin.stat:
    path: "{{ download_path }}/{{ stage_file_name }}"
  register: stage3_tarball

- name: Download Gentoo Stage 3 tarball
  get_url:
    url: "{{ gentoo_stage3_url }}"
    dest: "{{ download_path }}/{{ stage_file_name }}"
    timeout: 60
  when: not stage3_tarball.stat.exists

- name: Check if Gentoo Stage 3 checksum file exists
  ansible.builtin.stat:
    path: "{{ download_path }}/stage3.DIGESTS"
  register: stage3_digest

- name: Download Gentoo Stage 3 checksum file
  get_url:
    url: "{{ gentoo_checksum_url }}"
    dest: "{{ download_path }}/stage3.DIGESTS"
    timeout: 60
  when: not stage3_digest.stat.exists

- name: Verify SHA512 checksum
  shell: |
    cd "{{ download_path }}" && \
    grep -A 1 'SHA512 HASH' stage3.DIGESTS | \
    grep '{{ stage_file_name }}' | \
    grep -v 'CONTENT' | \
    sha512sum -c
  register: checksum_result
  failed_when: checksum_result.rc != 0

- name: Output verification result
  debug:
    msg: "Checksum verification passed"
  when: checksum_result is succeeded

- name: Extract Gentoo Stage 3 tarball
  become: yes
  ansible.builtin.unarchive:
    src: "{{ download_path }}/{{ stage_file_name }}"
    dest: "{{ base_mount_point }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1
